#!/usr/bin/env bash
#jdkw
# shellcheck disable=SC1091
PIDFILE="/tmp/myscript.pid"

echo $$ > "$PIDFILE"

sigterm_handler() {
    echo "I hate the kill command"
}

sigint_handler() {
    echo "Y U no love me?!"
}

cleanup_handler() {
    rm -f "$PIDFILE"
    exit 0
}

trap sigterm_handler SIGTERM
trap sigint_handler SIGINT
trap cleanup_handler SIGQUIT
trap cleanup_handler SIGTERM

while true
do
    echo "To infinity and beyond"
    sleep 2
done
