#!/usr/bin/env bash
#jdkw
# shellcheck disable=SC1091
PIDFILE="/tmp/myscript.pid"

# PID faylını yarat
echo $$ > "$PIDFILE"

# SIGTERM
sigterm_handler() {
    echo "I hate the kill command"
}

# SIGINT (Ctrl+C)
sigint_handler() {
    echo "Y U no love me?!"
}

# SIGQUIT və SIGTERM üçün cleanup
cleanup() {
    rm -f "$PIDFILE"
    exit 0
}

trap sigterm_handler SIGTERM
trap sigint_handler SIGINT
trap cleanup SIGQUIT
trap cleanup SIGTERM

# Sonsuz loop
while true
do
    echo "To infinity and beyond"
    sleep 2
done
