#!/usr/bin/env bash
#ksdkj
# shellcheck disable=SC1091
for pid in /proc/[0-9]*; do
    if [ -r "$pid/comm" ]; then
        name=$(cat "$pid/comm")
        case "$name" in
            *bash*)
                echo "$(basename "$pid") $name"
                ;;
        esac
    fi
done
